services:
  db:
    image: postgres:17-alpine
    container_name: ri-comp-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ctf
      POSTGRES_USER: ctf
      POSTGRES_PASSWORD: ctf2026
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
